## 切片

In [2]:
import numpy as np

In [15]:
a = np.arange(10)
print(a)
print(a[2])

[0 1 2 3 4 5 6 7 8 9]
2


In [4]:
# 含头不含尾
print(a[3:6])

[3 4 5]


In [5]:
# 从头开始截取到下标为3的位置(不含尾)
print(a[:3])

[0 1 2]


In [6]:
# 从下标为2的位置截取到结尾(含头)
print(a[3:])

[3 4 5 6 7 8 9]


In [10]:
# 步长为3，间隔截取(含头不含尾)
print(a[2:8:3])

[2 5]


## 翻转数组的小技巧

In [9]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


## 注意切片的数据和原始数据 共享(指向相同，一变都变)

In [16]:
# 切片赋值
print(a)
a[1:4] = 10, 20, 30
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30  4  5  6  7  8  9]


In [17]:
b = a[1:4]
b[0] = 90
print(a)
print(b)

[ 0 90 20 30  4  5  6  7  8  9]
[90 20 30]


### 二维数组切片 行 列

In [73]:
na = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(6)
print(na)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [77]:
print(na[[0, 1, 2]])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]]


In [79]:
# 行，再对行 取列
print(na[[0, 1, 2], [2, 3, 1]])

[ 2 13 21]


In [84]:
print(na[::2])

[[ 0  1  2  3  4  5]
 [20 21 22 23 24 25]
 [40 41 42 43 44 45]]


In [83]:
# 行步长，列步长
print(na[::2, ::2])

[[ 0  2  4]
 [20 22 24]
 [40 42 44]]


## 解决数据共享的问题, 也可用来copy数据

In [45]:
a = np.array([3, 1, 6, 4, 9 ,6 ,0])
print(a)
print(a.shape)
# a.size -> 7 a的长度
b = np.arange(0, a.size)
print(b)

[3 1 6 4 9 6 0]
(7,)
[0 1 2 3 4 5 6]


In [46]:
c = a[0: 2]
print(c)
c[0: 2] = 1, 2
print(a)

[3 1]
[1 2 6 4 9 6 0]


In [47]:
d = a[b]
print(d)

[1 2 6 4 9 6 0]


In [48]:
d[0] = 10
print(a)
type(a)

[1 2 6 4 9 6 0]


numpy.ndarray

In [49]:
print(d)
type(d)

[10  2  6  4  9  6  0]


numpy.ndarray

## 随机数和数据过滤

In [64]:
# o - 10 之间随机生成 3 个数，可写单个参数
a = np.random.randint(0, 10, 3)
print(a)

[2 7 1]


In [69]:
# 随机生成10 个 0 - 1 之间均匀分布的随机数
a = np.random.rand(10)
print(a)
print(a > 0.5)

[ 0.40224578  0.51191472  0.52481295  0.60375409  0.19980576  0.29768395
  0.40473807  0.67351988  0.40890391  0.57587367]
[False  True  True  True False False False  True False  True]


In [70]:
# 过滤，去除大于 0.5 的数
b = a[a > 0.5]
print(b)

[ 0.51191472  0.52481295  0.60375409  0.67351988  0.57587367]


In [71]:
# 将大于0.5的数重置为0.5， 并且 b 的数据不会受影响
a[a > 0.5] = 0.5
print(a)
print(b)

[ 0.40224578  0.5         0.5         0.5         0.19980576  0.29768395
  0.40473807  0.5         0.40890391  0.5       ]
[ 0.51191472  0.52481295  0.60375409  0.67351988  0.57587367]
