In [1]:
import math
import time
import numpy as np
# 画图
import matplotlib as mpl
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
# 统计
from scipy import stats
import scipy.optimize as opt
from scipy.stats import norm, poisson
# 解决画图中文乱码
mpl.rcParams['font.sans-serif'] = [u'SimHei']
mpl.rcParams['axes.unicode_minus'] = False

# arange reshape array

In [14]:
# 用于创建等差数组
# arange([start,] stop[, step,], dtype=None)
# 四个参数 start(起始点)， step(步长), dtype(返回类型)可省略
print(np.arange.__doc__)

arange([start,] stop[, step,], dtype=None)

    Return evenly spaced values within a given interval.

    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.

    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.

    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
    step : number, optional
        

In [2]:
# 行向量
# 0 - 60(含头不含尾) 起点，结尾，步长为10
a = np.arange(0, 60, 10)
print(a)
type(a)

[ 0 10 20 30 40 50]


numpy.ndarray

In [3]:
# reshape => 给予数组一个新的形状，而不改变它的数据
a_rsh = a.reshape((1, -1))
print(a_rsh)

[[ 0 10 20 30 40 50]]


In [4]:
# 转为列向量
a_rsh = a.reshape((-1, 1))
print(a_rsh)

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]


In [5]:
a_rsh_01 = a.reshape((2, 3))
print(a_rsh_01)

[[ 0 10 20]
 [30 40 50]]


In [6]:
b = np.array([0, 10, 20, 30, 40, 50])
print(b)
type(b)

[ 0 10 20 30 40 50]


numpy.ndarray

In [7]:
b_rsh = b.reshape((2, 3))
print(b_rsh)

[[ 0 10 20]
 [30 40 50]]


In [9]:
a = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(6)
print(a)
# 对比着看
print(np.arange(6))
print(np.arange(0, 60, 10))

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[0 1 2 3 4 5]
[ 0 10 20 30 40 50]


### 需要三个指针和三个整数对象，对于数值运算比较浪费内存和cpu, 所以使用Numpy提供的ndarray对象 -> np.array
* ### 存储单一数据类型的多维数组

In [13]:
a = [1, 2, 3]
a_ = np.array(a)
print(a_)
# 长度
print(a_.shape)
print(type(a_))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [15]:
b = np.array([[1, 2], [2, 3], [4, 5], [6, 7]])
print(b)
print(b.shape)

[[1 2]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


#### 强制修改shape，当某个轴为 -1 时，会将根据数组元素的个数自动计算此轴的长度

In [18]:
b.shape = (2, -1)
print(b)
print(b.shape)

[[1 2 2 3]
 [4 5 6 7]]
(2, 4)


In [21]:
b[0][2] = 1
print(b)

[[1 2 1 3]
 [4 5 6 7]]


#### reshape方法，可以创建改变了尺寸的新数组，原数组的shape保持不变，并且reshape之后的数组与原数组共享数据(一变都变)，设置的参数必须符合array的形状

In [24]:
c = b.reshape((4, -1))
print(c)
print(c.shape)

[[1 2]
 [1 3]
 [4 5]
 [6 7]]
(4, 2)


In [28]:
# 改 c
c[1][0] = 6
print(c)
print('-------')
# b 也变了
print(b)

[[1 2]
 [6 3]
 [4 5]
 [6 7]]
-------
[[1 2 6 3]
 [4 5 6 7]]
