In [13]:
import numpy as np

In [4]:
a = range(2, 10)
type(a)
for i in a:
    print(i)

2
3
4
5
6
7
8
9


In [5]:
for k, v in enumerate(a):
    print(k, v)

0 2
1 3
2 4
3 5
4 6
5 7
6 8
7 9


### 对比numpy.math和python标准库的math.sin计算速度

In [9]:
import time
import math

In [11]:
x = [i * 0.001 for i in range(100000)]
start = time.clock()
# enumerate => 枚举
# i 为索引，t 为值
for i, t in enumerate(x):
    x[i] = math.sin(t)
print(f"math.sin => {float(time.clock()) - float(start)}")

math.sin => 0.03701075559487599


In [15]:
a = np.array(x)
start = time.clock()
np.sin(x)
print(f"np.sin => {float(start) - float(time.clock())}")

np.sin => -0.0072714265430420255


```python
y = x1 + x2:	add(x1, x2 [, y])
y = x1 - x2:	subtract(x1, x2 [, y])
y = x1 * x2:	multiply (x1, x2 [, y])
y = x1 / x2:	divide (x1, x2 [, y]), 如果两个数组的元素为整数，那么用整数除法
y = x1 / x2:	true divide (x1, x2 [, y]), 总是返回精确的商
y = x1 // x2:	floor divide (x1, x2 [, y]), 总是对返回值取整
y = -x:	negative(x [,y])
y = x1**x2:	power(x1, x2 [, y])
y = x1 % x2:	remainder(x1, x2 [, y]), mod(x1, x2, [, y])
```

In [16]:
# 对应元素求和
a = np.arange(4)
a

array([0, 1, 2, 3])

In [17]:
b = np.arange(3, 7)
b

array([3, 4, 5, 6])

In [18]:
c = np.add(a, b)
c

array([3, 5, 7, 9])

In [ ]:
## ogrid 像一个多维数组，用 切片 作为下标进行存取，返回的是一组可以用来广播计算的数组

In [26]:
x = np.ogrid[0:5]
x

array([0, 1, 2, 3, 4])

## 线代

In [30]:
# linspace 函数创建爱你数组，parans -> 初值，终值，元素个数，是否包含终值(缺省为True)
# 第三个参数 => 将数据的分为 3 块
a = np.linspace(1, 10, 3);
a

array([  1. ,   5.5,  10. ])

In [31]:
b = np.linspace(1, 10, 4)
b

array([  1.,   4.,   7.,  10.])

In [33]:
d = np.linspace(1, 10, 5)
d

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [32]:
# 不包含终值
c = np.linspace(1, 10, 5, endpoint = False)
c

array([ 1. ,  2.8,  4.6,  6.4,  8.2])

## 对数

In [34]:
# 起始值为 10 ** 1, 终止值为 10 ** 2, 9 个数的等比数列，默认包含终止值
d = np.logspace(1, 2, 9)
d

array([  10.        ,   13.33521432,   17.7827941 ,   23.71373706,
         31.6227766 ,   42.16965034,   56.23413252,   74.98942093,  100.        ])

In [35]:
# 基础值修改为 2， 默认为 10
# 起始值 2 ** 0， 终止值 2 ** 10
g = np.logspace(0, 10, 5, base = 2)
g

array([  1.00000000e+00,   5.65685425e+00,   3.20000000e+01,
         1.81019336e+02,   1.02400000e+03])