## 切片

In [2]:
import numpy as np

In [15]:
a = np.arange(10)
print(a)
print(a[2])

[0 1 2 3 4 5 6 7 8 9]
2


In [4]:
# 含头不含尾
print(a[3:6])

[3 4 5]


In [5]:
# 从头开始截取到下标为3的位置(不含尾)
print(a[:3])

[0 1 2]


In [6]:
# 从下标为2的位置截取到结尾(含头)
print(a[3:])

[3 4 5 6 7 8 9]


In [10]:
# 步长为3，间隔截取(含头不含尾)
print(a[2:8:3])

[2 5]


## 翻转数组的小技巧

In [9]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


## 注意切片的数据和原始数据 共享(指向相同，一变都变)

In [16]:
# 切片赋值
print(a)
a[1:4] = 10, 20, 30
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30  4  5  6  7  8  9]


In [17]:
b = a[1:4]
b[0] = 90
print(a)
print(b)

[ 0 90 20 30  4  5  6  7  8  9]
[90 20 30]


## 解决数据共享的问题, 也可用来copy数据

In [45]:
a = np.array([3, 1, 6, 4, 9 ,6 ,0])
print(a)
print(a.shape)
# a.size -> 7 a的长度
b = np.arange(0, a.size)
print(b)

[3 1 6 4 9 6 0]
(7,)
[0 1 2 3 4 5 6]


In [46]:
c = a[0: 2]
print(c)
c[0: 2] = 1, 2
print(a)

[3 1]
[1 2 6 4 9 6 0]


In [47]:
d = a[b]
print(d)

[1 2 6 4 9 6 0]


In [48]:
d[0] = 10
print(a)
type(a)

[1 2 6 4 9 6 0]


numpy.ndarray

In [49]:
print(d)
type(d)

[10  2  6  4  9  6  0]


numpy.ndarray