In [13]:
import numpy as np

In [4]:
a = range(2, 10)
type(a)
for i in a:
    print(i)

2
3
4
5
6
7
8
9


In [5]:
for k, v in enumerate(a):
    print(k, v)

0 2
1 3
2 4
3 5
4 6
5 7
6 8
7 9


### 对比numpy.math和python标准库的math.sin计算速度

In [9]:
import time
import math

In [11]:
x = [i * 0.001 for i in range(100000)]
start = time.clock()
# enumerate => 枚举
# i 为索引，t 为值
for i, t in enumerate(x):
    x[i] = math.sin(t)
print(f"math.sin => {float(time.clock()) - float(start)}")

math.sin => 0.03701075559487599


In [15]:
a = np.array(x)
start = time.clock()
np.sin(x)
print(f"np.sin => {float(start) - float(time.clock())}")

np.sin => -0.0072714265430420255


```python
y = x1 + x2:	add(x1, x2 [, y])
y = x1 - x2:	subtract(x1, x2 [, y])
y = x1 * x2:	multiply (x1, x2 [, y])
y = x1 / x2:	divide (x1, x2 [, y]), 如果两个数组的元素为整数，那么用整数除法
y = x1 / x2:	true divide (x1, x2 [, y]), 总是返回精确的商
y = x1 // x2:	floor divide (x1, x2 [, y]), 总是对返回值取整
y = -x:	negative(x [,y])
y = x1**x2:	power(x1, x2 [, y])
y = x1 % x2:	remainder(x1, x2 [, y]), mod(x1, x2, [, y])
```

In [16]:
# 对应元素求和
a = np.arange(4)
a

array([0, 1, 2, 3])

In [17]:
b = np.arange(3, 7)
b

array([3, 4, 5, 6])

In [18]:
c = np.add(a, b)
c

array([3, 5, 7, 9])